"use client";

import { useEffect } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ChevronLeft, ChevronRight, X } from "lucide-react";
import type { GalleryProject } from "../types";

const surfaces = { gold: "from-stone-900 via-stone-700 to-amber-200", green: "from-emerald-950 via-emerald-800 to-emerald-200", plum: "from-stone-900 via-rose-950 to-rose-200", stone: "from-zinc-900 via-stone-600 to-stone-200" } as const;

function ModalArt({ project }: { project: GalleryProject }) { return <div className={`relative aspect-4/3 w-full overflow-hidden rounded-2xl bg-linear-to-br ${surfaces[project.accent]}`} role="img" aria-label={`${project.title} placeholder`}><div className="absolute -right-10 -top-10 size-[60%] rounded-full bg-white/20 blur-3xl" /><div className="absolute inset-[11%] rounded-[42%_42%_17%_17%] border border-white/25" /><div className="absolute inset-[22%] rounded-t-full border border-white/20 bg-white/10" /></div>; }

export function GalleryModal({ project, onClose, onPrevious, onNext }: { project: GalleryProject | null; onClose: () => void; onPrevious: () => void; onNext: () => void }) {
  const reducedMotion = useReducedMotion();
  useEffect(() => { if (!project) return; const handleKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); if (event.key === "ArrowLeft") onPrevious(); if (event.key === "ArrowRight") onNext(); }; window.addEventListener("keydown", handleKey); return () => window.removeEventListener("keydown", handleKey); }, [project, onClose, onPrevious, onNext]);
  return <AnimatePresence>{project && <motion.div role="dialog" aria-modal="true" aria-label={`${project.title} project details`} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-60 grid place-items-center bg-black/80 p-4 backdrop-blur-md" onClick={onClose}><motion.div initial={reducedMotion ? { opacity: 0 } : { opacity: 0, scale: .97, y: 14 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={reducedMotion ? { opacity: 0 } : { opacity: 0, scale: .97, y: 14 }} transition={{ duration: .3 }} className="relative w-full max-w-5xl rounded-[1.75rem] bg-card p-4 shadow-2xl sm:p-6" onClick={(event) => event.stopPropagation()}><button type="button" onClick={onClose} className="absolute right-8 top-8 z-10 grid size-10 place-items-center rounded-full bg-background/80 text-foreground shadow-sm backdrop-blur hover:bg-background focus-visible:outline-2 focus-visible:outline-ring" aria-label="Close project details"><X className="size-5" /></button><ModalArt project={project} /><div className="flex flex-col gap-6 px-2 pb-2 pt-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold tracking-[.2em] text-(--luxury-gold) uppercase">{project.category} · {project.frameStyle}</p><h2 className="mt-3 font-serif text-3xl sm:text-4xl">{project.title}</h2><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">{project.description}</p></div><div className="flex gap-2"><button type="button" onClick={onPrevious} className="grid size-11 place-items-center rounded-full border border-border hover:bg-muted focus-visible:outline-2 focus-visible:outline-ring" aria-label="Previous project"><ChevronLeft /></button><button type="button" onClick={onNext} className="grid size-11 place-items-center rounded-full border border-border hover:bg-muted focus-visible:outline-2 focus-visible:outline-ring" aria-label="Next project"><ChevronRight /></button></div></div></motion.div></motion.div>}</AnimatePresence>;
}
